#
# Copyright (c) 2020-2022 bluetulippon@gmail.com Chad_Peng(Pon).
# All Rights Reserved.
# Confidential and Proprietary - bluetulippon@gmail.com Chad_Peng(Pon).
#

#rm -rf panda/board/safety/safety_volkswagen.h
#rm -rf selfdrive/boardd/boardd.cc
#rm -rf selfdrive/common/params.cc
#rm -rf selfdrive/hardware/eon/hardware.h
#rm -rf selfdrive/ui/paint.cc
#rm -rf selfdrive/ui/qt/offroad/settings.cc
#rm -rf selfdrive/ui/qt/offroad/settings.h
#rm -rf selfdrive/ui/qt/util.cc
#rm -rf selfdrive/ui/qt/widgets/controls.h
#rm -rf selfdrive/ui/soundd/sound.cc
#rm -rf selfdrive/ui/soundd/sound.h
#rm -rf selfdrive/ui/ui.cc
#rm -rf selfdrive/ui/ui.h



##rm -rf ./cereal/car.capnp
##rm -rf ./cereal/log.capnp
#rm -rf ./cereal/gen/c/include/c++.capnp.h
#rm -rf ./cereal/gen/c/include/java.capnp.h
#rm -rf ./cereal/gen/cpp/car.capnp.h
#rm -rf ./cereal/gen/cpp/legacy.capnp.h
#rm -rf ./cereal/gen/cpp/log.capnp.h
#rm -rf ./cereal/logger/logger.h
#rm -rf ./cereal/messaging/bridge.cc
#rm -rf ./cereal/messaging/impl_msgq.cc
#rm -rf ./cereal/messaging/impl_msgq.h
#rm -rf ./cereal/messaging/impl_zmq.cc
#rm -rf ./cereal/messaging/impl_zmq.h
#rm -rf ./cereal/messaging/messaging.cc
#rm -rf ./cereal/messaging/messaging.h
#rm -rf ./cereal/messaging/messaging_pyx.cpp
#rm -rf ./cereal/messaging/msgq.cc
#rm -rf ./cereal/messaging/msgq.h
#rm -rf ./cereal/messaging/socketmaster.cc
#rm -rf ./cereal/services.h
#rm -rf ./cereal/visionipc/ipc.cc
#rm -rf ./cereal/visionipc/ipc.h
#rm -rf ./cereal/visionipc/test_runner.cc
#rm -rf ./cereal/visionipc/visionbuf.cc
#rm -rf ./cereal/visionipc/visionbuf.h
#rm -rf ./cereal/visionipc/visionbuf_cl.cc
#rm -rf ./cereal/visionipc/visionbuf_ion.cc
#rm -rf ./cereal/visionipc/visionipc.h
#rm -rf ./cereal/visionipc/visionipc_client.cc
#rm -rf ./cereal/visionipc/visionipc_client.h
#rm -rf ./cereal/visionipc/visionipc_pyx.cpp
#rm -rf ./cereal/visionipc/visionipc_server.cc
#rm -rf ./cereal/visionipc/visionipc_server.h
#rm -rf ./cereal/visionipc/visionipc_tests.cc
#rm -rf ./common/clock.cpp
#rm -rf ./common/kalman/simple_kalman_impl.cpp
#rm -rf ./common/params_pyx.cpp
#rm -rf ./common/transformations/coordinates.cc
#rm -rf ./common/transformations/coordinates.hpp
#rm -rf ./common/transformations/orientation.cc
#rm -rf ./common/transformations/orientation.hpp
#rm -rf ./common/transformations/transformations.cpp
#rm -rf ./installer/updater/updater.cc
#rm -rf ./opendbc/can/common.cc
#rm -rf ./opendbc/can/common.h
#rm -rf ./opendbc/can/common_dbc.h
#rm -rf ./opendbc/can/dbc.cc
#rm -rf ./opendbc/can/dbc_out/acura_ilx_2016_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/acura_rdx_2018_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/acura_rdx_2020_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/chrysler_pacifica_2017_hybrid.cc
#rm -rf ./opendbc/can/dbc_out/chrysler_pacifica_2017_hybrid_private_fusion.cc
#rm -rf ./opendbc/can/dbc_out/ford_fusion_2018_adas.cc
#rm -rf ./opendbc/can/dbc_out/ford_fusion_2018_pt.cc
#rm -rf ./opendbc/can/dbc_out/gm_global_a_chassis.cc
#rm -rf ./opendbc/can/dbc_out/gm_global_a_object.cc
#rm -rf ./opendbc/can/dbc_out/gm_global_a_powertrain.cc
#rm -rf ./opendbc/can/dbc_out/honda_accord_2018_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_accord_lx15t_2018_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_accord_s2t_2018_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_civic_hatchback_ex_2017_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_civic_sedan_16_diesel_2019_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_civic_touring_2016_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_crv_ex_2017_body_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_crv_ex_2017_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_crv_executive_2016_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_crv_hybrid_2019_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_crv_touring_2016_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_fit_ex_2018_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_hrv_touring_2019_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_insight_ex_2019_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_odyssey_exl_2018_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_odyssey_extreme_edition_2018_china_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_pilot_touring_2017_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/honda_ridgeline_black_edition_2017_can_generated.cc
#rm -rf ./opendbc/can/dbc_out/hyundai_kia_generic.cc
#rm -rf ./opendbc/can/dbc_out/lexus_ct200h_2018_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/lexus_is_2018_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/lexus_nx300_2018_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/lexus_nx300h_2018_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/lexus_rx_350_2016_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/lexus_rx_hybrid_2017_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/mazda_2017.cc
#rm -rf ./opendbc/can/dbc_out/nissan_leaf_2018.cc
#rm -rf ./opendbc/can/dbc_out/nissan_x_trail_2017.cc
#rm -rf ./opendbc/can/dbc_out/subaru_forester_2017_generated.cc
#rm -rf ./opendbc/can/dbc_out/subaru_global_2017_generated.cc
#rm -rf ./opendbc/can/dbc_out/subaru_outback_2015_generated.cc
#rm -rf ./opendbc/can/dbc_out/subaru_outback_2019_generated.cc
#rm -rf ./opendbc/can/dbc_out/tesla_can.cc
#rm -rf ./opendbc/can/dbc_out/tesla_radar.cc
#rm -rf ./opendbc/can/dbc_out/toyota_adas.cc
#rm -rf ./opendbc/can/dbc_out/toyota_avalon_2017_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_camry_hybrid_2018_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_corolla_2017_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_highlander_2017_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_highlander_hybrid_2018_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_nodsu_hybrid_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_nodsu_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_prius_2017_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_rav4_2017_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_rav4_hybrid_2017_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_sienna_xle_2018_pt_generated.cc
#rm -rf ./opendbc/can/dbc_out/toyota_tss2_adas.cc
#rm -rf ./opendbc/can/dbc_out/vw_mqb_2010.cc
#rm -rf ./opendbc/can/dbc_template.cc
#rm -rf ./opendbc/can/packer.cc
#rm -rf ./opendbc/can/packer_pyx.cpp
#rm -rf ./opendbc/can/parser.cc
#rm -rf ./opendbc/can/parser_pyx.cpp
#rm -rf ./panda/board/boards/black.h
#rm -rf ./panda/board/boards/board_declarations.h
#rm -rf ./panda/board/boards/dos.h
#rm -rf ./panda/board/boards/grey.h
#rm -rf ./panda/board/boards/pedal.h
#rm -rf ./panda/board/boards/red.h
#rm -rf ./panda/board/boards/uno.h
#rm -rf ./panda/board/boards/unused_funcs.h
#rm -rf ./panda/board/boards/white.h
#rm -rf ./panda/board/bootstub.c
#rm -rf ./panda/board/bootstub_declarations.h
#rm -rf ./panda/board/config.h
#rm -rf ./panda/board/crc.h
#rm -rf ./panda/board/critical.h
#rm -rf ./panda/board/drivers/bxcan.h
#rm -rf ./panda/board/drivers/can_common.h
#rm -rf ./panda/board/drivers/fan.h
#rm -rf ./panda/board/drivers/fdcan.h
#rm -rf ./panda/board/drivers/gmlan_alt.h
#rm -rf ./panda/board/drivers/gpio.h
#rm -rf ./panda/board/drivers/harness.h
#rm -rf ./panda/board/drivers/interrupts.h
#rm -rf ./panda/board/drivers/kline_init.h
#rm -rf ./panda/board/drivers/pwm.h
#rm -rf ./panda/board/drivers/registers.h
#rm -rf ./panda/board/drivers/rtc.h
#rm -rf ./panda/board/drivers/timers.h
#rm -rf ./panda/board/drivers/uart.h
#rm -rf ./panda/board/drivers/usb.h
#rm -rf ./panda/board/early_init.h
#rm -rf ./panda/board/faults.h
#rm -rf ./panda/board/flasher.h
#rm -rf ./panda/board/libc.h
#rm -rf ./panda/board/main.c
#rm -rf ./panda/board/main_declarations.h
#rm -rf ./panda/board/obj/cert.h
#rm -rf ./panda/board/obj/gitversion.h
#rm -rf ./panda/board/pedal/main.c
#rm -rf ./panda/board/pedal/main_declarations.h
#rm -rf ./panda/board/power_saving.h
#rm -rf ./panda/board/provision.h
#rm -rf ./panda/board/safety.h
#rm -rf ./panda/board/safety/safety_chrysler.h
#rm -rf ./panda/board/safety/safety_defaults.h
#rm -rf ./panda/board/safety/safety_elm327.h
#rm -rf ./panda/board/safety/safety_ford.h
#rm -rf ./panda/board/safety/safety_gm.h
#rm -rf ./panda/board/safety/safety_gm_ascm.h
#rm -rf ./panda/board/safety/safety_honda.h
#rm -rf ./panda/board/safety/safety_hyundai.h
#rm -rf ./panda/board/safety/safety_mazda.h
#rm -rf ./panda/board/safety/safety_nissan.h
#rm -rf ./panda/board/safety/safety_subaru.h
#rm -rf ./panda/board/safety/safety_tesla.h
#rm -rf ./panda/board/safety/safety_toyota.h
#rm -rf ./panda/board/safety/safety_volkswagen.h
#rm -rf ./panda/board/safety_declarations.h
#rm -rf ./panda/board/stm32fx/board.h
#rm -rf ./panda/board/stm32fx/clock.h
#rm -rf ./panda/board/stm32fx/clock_source.h
#rm -rf ./panda/board/stm32fx/inc/cmsis_compiler.h
#rm -rf ./panda/board/stm32fx/inc/cmsis_gcc.h
#rm -rf ./panda/board/stm32fx/inc/cmsis_version.h
#rm -rf ./panda/board/stm32fx/inc/core_cm3.h
#rm -rf ./panda/board/stm32fx/inc/core_cm4.h
#rm -rf ./panda/board/stm32fx/inc/mpu_armv7.h
#rm -rf ./panda/board/stm32fx/inc/stm32f205xx.h
#rm -rf ./panda/board/stm32fx/inc/stm32f2xx.h
#rm -rf ./panda/board/stm32fx/inc/stm32f2xx_hal_def.h
#rm -rf ./panda/board/stm32fx/inc/stm32f2xx_hal_gpio_ex.h
#rm -rf ./panda/board/stm32fx/inc/stm32f413xx.h
#rm -rf ./panda/board/stm32fx/inc/stm32f4xx.h
#rm -rf ./panda/board/stm32fx/inc/stm32f4xx_hal_def.h
#rm -rf ./panda/board/stm32fx/inc/stm32f4xx_hal_gpio_ex.h
#rm -rf ./panda/board/stm32fx/inc/system_stm32f2xx.h
#rm -rf ./panda/board/stm32fx/inc/system_stm32f4xx.h
#rm -rf ./panda/board/stm32fx/interrupt_handlers.h
#rm -rf ./panda/board/stm32fx/lladc.h
#rm -rf ./panda/board/stm32fx/llbxcan.h
#rm -rf ./panda/board/stm32fx/lldac.h
#rm -rf ./panda/board/stm32fx/llfan.h
#rm -rf ./panda/board/stm32fx/llflash.h
#rm -rf ./panda/board/stm32fx/llrtc.h
#rm -rf ./panda/board/stm32fx/llspi.h
#rm -rf ./panda/board/stm32fx/lluart.h
#rm -rf ./panda/board/stm32fx/llusb.h
#rm -rf ./panda/board/stm32fx/peripherals.h
#rm -rf ./panda/board/stm32fx/stm32fx_config.h
#rm -rf ./panda/board/stm32h7/board.h
#rm -rf ./panda/board/stm32h7/clock.h
#rm -rf ./panda/board/stm32h7/inc/cmsis_compiler.h
#rm -rf ./panda/board/stm32h7/inc/cmsis_gcc.h
#rm -rf ./panda/board/stm32h7/inc/cmsis_version.h
#rm -rf ./panda/board/stm32h7/inc/core_cm7.h
#rm -rf ./panda/board/stm32h7/inc/mpu_armv8.h
#rm -rf ./panda/board/stm32h7/inc/stm32h725xx.h
#rm -rf ./panda/board/stm32h7/inc/stm32h735xx.h
#rm -rf ./panda/board/stm32h7/inc/stm32h7xx.h
#rm -rf ./panda/board/stm32h7/inc/stm32h7xx_hal_def.h
#rm -rf ./panda/board/stm32h7/inc/stm32h7xx_hal_gpio_ex.h
#rm -rf ./panda/board/stm32h7/inc/system_stm32h7xx.h
#rm -rf ./panda/board/stm32h7/interrupt_handlers.h
#rm -rf ./panda/board/stm32h7/lladc.h
#rm -rf ./panda/board/stm32h7/llfan.h
#rm -rf ./panda/board/stm32h7/llfdcan.h
#rm -rf ./panda/board/stm32h7/llflash.h
#rm -rf ./panda/board/stm32h7/llrtc.h
#rm -rf ./panda/board/stm32h7/lluart.h
#rm -rf ./panda/board/stm32h7/llusb.h
#rm -rf ./panda/board/stm32h7/peripherals.h
#rm -rf ./panda/board/stm32h7/stm32h7_config.h
#rm -rf ./panda/board/tests/test_rsa.c
#rm -rf ./panda/crypto/hash-internal.h
#rm -rf ./panda/crypto/rsa.c
#rm -rf ./panda/crypto/rsa.h
#rm -rf ./panda/crypto/sha.c
#rm -rf ./panda/crypto/sha.h
#rm -rf ./panda/crypto/stdint.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/asset_manager.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/asset_manager_jni.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/bitmap.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/configuration.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/input.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/keycodes.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/looper.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/multinetwork.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/native_activity.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/native_window.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/native_window_jni.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/obb.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/rect.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/sensor.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/storage_manager.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/trace.h
#rm -rf ./phonelibs/android_frameworks_native/include/android/window.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/AppOpsManager.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/Binder.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/BinderService.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/BpBinder.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/BufferedTextOutput.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/Debug.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IAppOpsCallback.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IAppOpsService.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IBatteryStats.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IBinder.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IInterface.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IMemory.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IPCThreadState.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IPermissionController.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IProcessInfoService.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/IServiceManager.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/MemoryBase.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/MemoryDealer.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/MemoryHeapBase.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/MemoryHeapIon.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/Parcel.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/PermissionCache.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/ProcessInfoService.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/ProcessState.h
#rm -rf ./phonelibs/android_frameworks_native/include/binder/TextOutput.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BitTube.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferItem.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferItemConsumer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferQueue.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferQueueConsumer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferQueueCore.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferQueueDefs.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferQueueProducer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/BufferSlot.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/ConsumerBase.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/CpuConsumer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/DisplayEventReceiver.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/GLConsumer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/GraphicBufferAlloc.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/GuiConfig.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/IConsumerListener.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/IDisplayEventConnection.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/IGraphicBufferAlloc.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/IGraphicBufferConsumer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/IGraphicBufferProducer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/IProducerListener.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/ISensorEventConnection.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/ISensorServer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/ISurfaceComposer.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/ISurfaceComposerClient.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/Sensor.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/SensorEventQueue.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/SensorManager.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/StreamSplitter.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/Surface.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/SurfaceComposerClient.h
#rm -rf ./phonelibs/android_frameworks_native/include/gui/SurfaceControl.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/ANativeObjectBase.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/DisplayInfo.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/DisplayStatInfo.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/Fence.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/FramebufferNativeWindow.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/FrameStats.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/GraphicBuffer.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/GraphicBufferAllocator.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/GraphicBufferMapper.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/mat4.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/PixelFormat.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/Point.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/Rect.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/Region.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/TMatHelpers.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/TVecHelpers.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/UiConfig.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/vec2.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/vec3.h
#rm -rf ./phonelibs/android_frameworks_native/include/ui/vec4.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/activity_recognition.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/audio.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/audio_alsaops.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/audio_amplifier.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/audio_effect.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/audio_policy.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bluetooth.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_av.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_common_types.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_gatt.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_gatt_client.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_gatt_server.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_gatt_types.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_hd.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_hf.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_hf_client.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_hh.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_hl.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_mce.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_pan.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_rc.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_sdp.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/bt_sock.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/camera.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/camera_common.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/camera2.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/camera3.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/consumerir.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/display_defs.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/fb.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/fingerprint.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/fused_location.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/gatekeeper.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/gps.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/gralloc.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/hardware.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/hdmi_cec.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/hw_auth_token.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/hwcomposer.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/hwcomposer_defs.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/input.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/keymaster_common.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/keymaster_defs.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/keymaster0.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/keymaster1.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/lights.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/local_time_hal.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/memtrack.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/nfc.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/nfc_tag.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/power.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/qemu_pipe.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/qemud.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/radio.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/sensors.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/sound_trigger.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/tv_input.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/vibrator.h
#rm -rf ./phonelibs/android_hardware_libhardware/include/hardware/wipower.h
#rm -rf ./phonelibs/android_system_core/include/cutils/android_reboot.h
#rm -rf ./phonelibs/android_system_core/include/cutils/aref.h
#rm -rf ./phonelibs/android_system_core/include/cutils/ashmem.h
#rm -rf ./phonelibs/android_system_core/include/cutils/atomic.h
#rm -rf ./phonelibs/android_system_core/include/cutils/bitops.h
#rm -rf ./phonelibs/android_system_core/include/cutils/compiler.h
#rm -rf ./phonelibs/android_system_core/include/cutils/config_utils.h
#rm -rf ./phonelibs/android_system_core/include/cutils/debugger.h
#rm -rf ./phonelibs/android_system_core/include/cutils/fs.h
#rm -rf ./phonelibs/android_system_core/include/cutils/hashmap.h
#rm -rf ./phonelibs/android_system_core/include/cutils/iosched_policy.h
#rm -rf ./phonelibs/android_system_core/include/cutils/jstring.h
#rm -rf ./phonelibs/android_system_core/include/cutils/klog.h
#rm -rf ./phonelibs/android_system_core/include/cutils/list.h
#rm -rf ./phonelibs/android_system_core/include/cutils/log.h
#rm -rf ./phonelibs/android_system_core/include/cutils/memory.h
#rm -rf ./phonelibs/android_system_core/include/cutils/misc.h
#rm -rf ./phonelibs/android_system_core/include/cutils/multiuser.h
#rm -rf ./phonelibs/android_system_core/include/cutils/native_handle.h
#rm -rf ./phonelibs/android_system_core/include/cutils/open_memstream.h
#rm -rf ./phonelibs/android_system_core/include/cutils/partition_utils.h
#rm -rf ./phonelibs/android_system_core/include/cutils/process_name.h
#rm -rf ./phonelibs/android_system_core/include/cutils/properties.h
#rm -rf ./phonelibs/android_system_core/include/cutils/qtaguid.h
#rm -rf ./phonelibs/android_system_core/include/cutils/record_stream.h
#rm -rf ./phonelibs/android_system_core/include/cutils/sched_policy.h
#rm -rf ./phonelibs/android_system_core/include/cutils/sockets.h
#rm -rf ./phonelibs/android_system_core/include/cutils/str_parms.h
#rm -rf ./phonelibs/android_system_core/include/cutils/threads.h
#rm -rf ./phonelibs/android_system_core/include/cutils/trace.h
#rm -rf ./phonelibs/android_system_core/include/cutils/uevent.h
#rm -rf ./phonelibs/android_system_core/include/log/event_tag_map.h
#rm -rf ./phonelibs/android_system_core/include/log/log.h
#rm -rf ./phonelibs/android_system_core/include/log/log_read.h
#rm -rf ./phonelibs/android_system_core/include/log/logd.h
#rm -rf ./phonelibs/android_system_core/include/log/logger.h
#rm -rf ./phonelibs/android_system_core/include/log/logprint.h
#rm -rf ./phonelibs/android_system_core/include/log/uio.h
#rm -rf ./phonelibs/android_system_core/include/system/camera.h
#rm -rf ./phonelibs/android_system_core/include/system/graphics.h
#rm -rf ./phonelibs/android_system_core/include/system/radio.h
#rm -rf ./phonelibs/android_system_core/include/system/thread_defs.h
#rm -rf ./phonelibs/android_system_core/include/system/window.h
#rm -rf ./phonelibs/android_system_core/include/utils/AndroidThreads.h
#rm -rf ./phonelibs/android_system_core/include/utils/ashmem.h
#rm -rf ./phonelibs/android_system_core/include/utils/Atomic.h
#rm -rf ./phonelibs/android_system_core/include/utils/BasicHashtable.h
#rm -rf ./phonelibs/android_system_core/include/utils/BitSet.h
#rm -rf ./phonelibs/android_system_core/include/utils/BlobCache.h
#rm -rf ./phonelibs/android_system_core/include/utils/ByteOrder.h
#rm -rf ./phonelibs/android_system_core/include/utils/CallStack.h
#rm -rf ./phonelibs/android_system_core/include/utils/Compat.h
#rm -rf ./phonelibs/android_system_core/include/utils/Condition.h
#rm -rf ./phonelibs/android_system_core/include/utils/Debug.h
#rm -rf ./phonelibs/android_system_core/include/utils/Endian.h
#rm -rf ./phonelibs/android_system_core/include/utils/Errors.h
#rm -rf ./phonelibs/android_system_core/include/utils/FileMap.h
#rm -rf ./phonelibs/android_system_core/include/utils/Flattenable.h
#rm -rf ./phonelibs/android_system_core/include/utils/Functor.h
#rm -rf ./phonelibs/android_system_core/include/utils/JenkinsHash.h
#rm -rf ./phonelibs/android_system_core/include/utils/KeyedVector.h
#rm -rf ./phonelibs/android_system_core/include/utils/LinearTransform.h
#rm -rf ./phonelibs/android_system_core/include/utils/List.h
#rm -rf ./phonelibs/android_system_core/include/utils/Log.h
#rm -rf ./phonelibs/android_system_core/include/utils/Looper.h
#rm -rf ./phonelibs/android_system_core/include/utils/LruCache.h
#rm -rf ./phonelibs/android_system_core/include/utils/misc.h
#rm -rf ./phonelibs/android_system_core/include/utils/Mutex.h
#rm -rf ./phonelibs/android_system_core/include/utils/NativeHandle.h
#rm -rf ./phonelibs/android_system_core/include/utils/Printer.h
#rm -rf ./phonelibs/android_system_core/include/utils/ProcessCallStack.h
#rm -rf ./phonelibs/android_system_core/include/utils/PropertyMap.h
#rm -rf ./phonelibs/android_system_core/include/utils/RefBase.h
#rm -rf ./phonelibs/android_system_core/include/utils/RWLock.h
#rm -rf ./phonelibs/android_system_core/include/utils/SharedBuffer.h
#rm -rf ./phonelibs/android_system_core/include/utils/Singleton.h
#rm -rf ./phonelibs/android_system_core/include/utils/SortedVector.h
#rm -rf ./phonelibs/android_system_core/include/utils/StopWatch.h
#rm -rf ./phonelibs/android_system_core/include/utils/String16.h
#rm -rf ./phonelibs/android_system_core/include/utils/String8.h
#rm -rf ./phonelibs/android_system_core/include/utils/StrongPointer.h
#rm -rf ./phonelibs/android_system_core/include/utils/SystemClock.h
#rm -rf ./phonelibs/android_system_core/include/utils/Thread.h
#rm -rf ./phonelibs/android_system_core/include/utils/ThreadDefs.h
#rm -rf ./phonelibs/android_system_core/include/utils/threads.h
#rm -rf ./phonelibs/android_system_core/include/utils/Timers.h
#rm -rf ./phonelibs/android_system_core/include/utils/Tokenizer.h
#rm -rf ./phonelibs/android_system_core/include/utils/Trace.h
#rm -rf ./phonelibs/android_system_core/include/utils/TypeHelpers.h
#rm -rf ./phonelibs/android_system_core/include/utils/Unicode.h
#rm -rf ./phonelibs/android_system_core/include/utils/Vector.h
#rm -rf ./phonelibs/android_system_core/include/utils/VectorImpl.h
#rm -rf ./phonelibs/bzip2/bzlib.h
#rm -rf ./phonelibs/json11/json11.cpp
#rm -rf ./phonelibs/json11/json11.hpp
#rm -rf ./phonelibs/kaitai/custom_decoder.h
#rm -rf ./phonelibs/kaitai/exceptions.h
#rm -rf ./phonelibs/kaitai/kaitaistream.cpp
#rm -rf ./phonelibs/kaitai/kaitaistream.h
#rm -rf ./phonelibs/kaitai/kaitaistruct.h
#rm -rf ./phonelibs/libgralloc/include/gralloc_priv.h
#rm -rf ./phonelibs/libyuv/include/libyuv.h
#rm -rf ./phonelibs/libyuv/include/libyuv/basic_types.h
#rm -rf ./phonelibs/libyuv/include/libyuv/compare.h
#rm -rf ./phonelibs/libyuv/include/libyuv/compare_row.h
#rm -rf ./phonelibs/libyuv/include/libyuv/convert.h
#rm -rf ./phonelibs/libyuv/include/libyuv/convert_argb.h
#rm -rf ./phonelibs/libyuv/include/libyuv/convert_from.h
#rm -rf ./phonelibs/libyuv/include/libyuv/convert_from_argb.h
#rm -rf ./phonelibs/libyuv/include/libyuv/cpu_id.h
#rm -rf ./phonelibs/libyuv/include/libyuv/macros_msa.h
#rm -rf ./phonelibs/libyuv/include/libyuv/mjpeg_decoder.h
#rm -rf ./phonelibs/libyuv/include/libyuv/planar_functions.h
#rm -rf ./phonelibs/libyuv/include/libyuv/rotate.h
#rm -rf ./phonelibs/libyuv/include/libyuv/rotate_argb.h
#rm -rf ./phonelibs/libyuv/include/libyuv/rotate_row.h
#rm -rf ./phonelibs/libyuv/include/libyuv/row.h
#rm -rf ./phonelibs/libyuv/include/libyuv/scale.h
#rm -rf ./phonelibs/libyuv/include/libyuv/scale_argb.h
#rm -rf ./phonelibs/libyuv/include/libyuv/scale_row.h
#rm -rf ./phonelibs/libyuv/include/libyuv/version.h
#rm -rf ./phonelibs/libyuv/include/libyuv/video_common.h
#rm -rf ./phonelibs/linux/include/linux/ion.h
#rm -rf ./phonelibs/linux/include/msm_ion.h
#rm -rf ./phonelibs/mapbox-gl-native-qt/include/qmapbox.hpp
#rm -rf ./phonelibs/mapbox-gl-native-qt/include/QMapboxGL
#rm -rf ./phonelibs/mapbox-gl-native-qt/include/qmapboxgl.hpp
#rm -rf ./phonelibs/nanovg/fontstash.h
#rm -rf ./phonelibs/nanovg/nanovg.c
#rm -rf ./phonelibs/nanovg/nanovg.h
#rm -rf ./phonelibs/nanovg/nanovg.o
#rm -rf ./phonelibs/nanovg/nanovg_gl.h
#rm -rf ./phonelibs/nanovg/nanovg_gl_utils.h
#rm -rf ./phonelibs/nanovg/stb_image.h
#rm -rf ./phonelibs/nanovg/stb_truetype.h
#rm -rf ./phonelibs/opencl/include/CL/cl.h
#rm -rf ./phonelibs/opencl/include/CL/cl_d3d10.h
#rm -rf ./phonelibs/opencl/include/CL/cl_d3d11.h
#rm -rf ./phonelibs/opencl/include/CL/cl_dx9_media_sharing.h
#rm -rf ./phonelibs/opencl/include/CL/cl_egl.h
#rm -rf ./phonelibs/opencl/include/CL/cl_ext.h
#rm -rf ./phonelibs/opencl/include/CL/cl_ext_qcom.h
#rm -rf ./phonelibs/opencl/include/CL/cl_gl.h
#rm -rf ./phonelibs/opencl/include/CL/cl_gl_ext.h
#rm -rf ./phonelibs/opencl/include/CL/cl_platform.h
#rm -rf ./phonelibs/opencl/include/CL/opencl.h
#rm -rf ./phonelibs/openmax/include/OMX_Audio.h
#rm -rf ./phonelibs/openmax/include/OMX_Component.h
#rm -rf ./phonelibs/openmax/include/OMX_ContentPipe.h
#rm -rf ./phonelibs/openmax/include/OMX_Core.h
#rm -rf ./phonelibs/openmax/include/OMX_CoreExt.h
#rm -rf ./phonelibs/openmax/include/OMX_Image.h
#rm -rf ./phonelibs/openmax/include/OMX_Index.h
#rm -rf ./phonelibs/openmax/include/OMX_IndexExt.h
#rm -rf ./phonelibs/openmax/include/OMX_IVCommon.h
#rm -rf ./phonelibs/openmax/include/OMX_Other.h
#rm -rf ./phonelibs/openmax/include/OMX_QCOMExtns.h
#rm -rf ./phonelibs/openmax/include/OMX_Skype_VideoExtensions.h
#rm -rf ./phonelibs/openmax/include/OMX_Types.h
#rm -rf ./phonelibs/openmax/include/OMX_Video.h
#rm -rf ./phonelibs/openmax/include/OMX_VideoExt.h
#rm -rf ./phonelibs/qpoases/EXAMPLES/example1.cpp
#rm -rf ./phonelibs/qpoases/EXAMPLES/example1b.cpp
#rm -rf ./phonelibs/qpoases/INCLUDE/Bounds.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/Constants.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/Constraints.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/CyclingManager.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/EXTRAS/SolutionAnalysis.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/Indexlist.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/MessageHandling.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/QProblem.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/QProblemB.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/SubjectTo.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/Types.hpp
#rm -rf ./phonelibs/qpoases/INCLUDE/Utils.hpp
#rm -rf ./phonelibs/qpoases/SRC/Bounds.cpp
#rm -rf ./phonelibs/qpoases/SRC/Constraints.cpp
#rm -rf ./phonelibs/qpoases/SRC/CyclingManager.cpp
#rm -rf ./phonelibs/qpoases/SRC/EXTRAS/SolutionAnalysis.cpp
#rm -rf ./phonelibs/qpoases/SRC/Indexlist.cpp
#rm -rf ./phonelibs/qpoases/SRC/MessageHandling.cpp
#rm -rf ./phonelibs/qpoases/SRC/QProblem.cpp
#rm -rf ./phonelibs/qpoases/SRC/QProblemB.cpp
#rm -rf ./phonelibs/qpoases/SRC/SubjectTo.cpp
#rm -rf ./phonelibs/qpoases/SRC/Utils.cpp
#rm -rf ./phonelibs/qrcode/QrCode.cc
#rm -rf ./phonelibs/qrcode/QrCode.hpp
#rm -rf ./phonelibs/snpe/include/DiagLog/IDiagLog.hpp
#rm -rf ./phonelibs/snpe/include/DiagLog/Options.hpp
#rm -rf ./phonelibs/snpe/include/DlContainer/IDlContainer.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/DlEnums.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/DlError.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/DlOptional.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/DlVersion.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/IBufferAttributes.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/ITensor.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/ITensorFactory.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/ITensorItr.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/ITensorItrImpl.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/IUDL.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/IUserBuffer.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/IUserBufferFactory.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/PlatformConfig.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/RuntimeList.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/String.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/StringList.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/TensorMap.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/TensorShape.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/TensorShapeMap.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/UDLContext.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/UDLFunc.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/UserBufferMap.hpp
#rm -rf ./phonelibs/snpe/include/DlSystem/ZdlExportDefine.hpp
#rm -rf ./phonelibs/snpe/include/PlatformValidator/PlatformValidator.hpp
#rm -rf ./phonelibs/snpe/include/SNPE/ApplicationBufferMap.hpp
#rm -rf ./phonelibs/snpe/include/SNPE/PSNPE.hpp
#rm -rf ./phonelibs/snpe/include/SNPE/RuntimeConfigList.hpp
#rm -rf ./phonelibs/snpe/include/SNPE/SNPE.hpp
#rm -rf ./phonelibs/snpe/include/SNPE/SNPEBuilder.hpp
#rm -rf ./phonelibs/snpe/include/SNPE/SNPEFactory.hpp
#rm -rf ./phonelibs/snpe/include/SNPE/UserBufferList.hpp
#rm -rf ./phonelibs/snpe/include/SnpeUdo/UdoBase.h
#rm -rf ./phonelibs/snpe/include/SnpeUdo/UdoImpl.h
#rm -rf ./phonelibs/snpe/include/SnpeUdo/UdoImplCpu.h
#rm -rf ./phonelibs/snpe/include/SnpeUdo/UdoImplDsp.h
#rm -rf ./phonelibs/snpe/include/SnpeUdo/UdoImplGpu.h
#rm -rf ./phonelibs/snpe/include/SnpeUdo/UdoReg.h
#rm -rf ./phonelibs/snpe/include/SnpeUdo/UdoShared.h
#rm -rf ./rednose/helpers/common_ekf.cc
#rm -rf ./rednose/helpers/common_ekf.h
#rm -rf ./rednose/helpers/ekf_sym.cc
#rm -rf ./rednose/helpers/ekf_sym.h
#rm -rf ./rednose/helpers/ekf_sym_pyx.cpp
#rm -rf ./rednose/templates/compute_pos.c
#rm -rf ./rednose/templates/ekf_c.c
#rm -rf ./rednose/templates/feature_handler.c
rm -rf ./selfdrive/boardd/boardd.cc
#rm -rf ./selfdrive/boardd/boardd_api_impl.cpp
#rm -rf ./selfdrive/boardd/can_list_to_can_capnp.cc
rm -rf ./selfdrive/boardd/panda.cc
#rm -rf ./selfdrive/boardd/panda.h
#rm -rf ./selfdrive/boardd/pigeon.cc
#rm -rf ./selfdrive/boardd/pigeon.h
#rm -rf ./selfdrive/camerad/cameras/camera_common.cc
#rm -rf ./selfdrive/camerad/cameras/camera_common.h
#rm -rf ./selfdrive/camerad/cameras/camera_frame_stream.cc
#rm -rf ./selfdrive/camerad/cameras/camera_frame_stream.h
#rm -rf ./selfdrive/camerad/cameras/camera_qcom.cc
#rm -rf ./selfdrive/camerad/cameras/camera_qcom.h
#rm -rf ./selfdrive/camerad/cameras/camera_qcom2.cc
#rm -rf ./selfdrive/camerad/cameras/camera_qcom2.h
#rm -rf ./selfdrive/camerad/cameras/debayer.cl
#rm -rf ./selfdrive/camerad/cameras/real_debayer.cl
#rm -rf ./selfdrive/camerad/cameras/sensor_i2c.h
#rm -rf ./selfdrive/camerad/cameras/sensor2_i2c.h
#rm -rf ./selfdrive/camerad/imgproc/conv.cl
#rm -rf ./selfdrive/camerad/imgproc/pool.cl
#rm -rf ./selfdrive/camerad/imgproc/utils.cc
#rm -rf ./selfdrive/camerad/imgproc/utils.h
#rm -rf ./selfdrive/camerad/include/media/cam_cpas.h
#rm -rf ./selfdrive/camerad/include/media/cam_defs.h
#rm -rf ./selfdrive/camerad/include/media/cam_fd.h
#rm -rf ./selfdrive/camerad/include/media/cam_icp.h
#rm -rf ./selfdrive/camerad/include/media/cam_isp.h
#rm -rf ./selfdrive/camerad/include/media/cam_isp_ife.h
#rm -rf ./selfdrive/camerad/include/media/cam_isp_vfe.h
#rm -rf ./selfdrive/camerad/include/media/cam_jpeg.h
#rm -rf ./selfdrive/camerad/include/media/cam_lrme.h
#rm -rf ./selfdrive/camerad/include/media/cam_req_mgr.h
#rm -rf ./selfdrive/camerad/include/media/cam_sensor.h
#rm -rf ./selfdrive/camerad/include/media/cam_sensor_cmn_header.h
#rm -rf ./selfdrive/camerad/include/media/cam_sync.h
#rm -rf ./selfdrive/camerad/include/msm_cam_sensor.h
#rm -rf ./selfdrive/camerad/include/msm_camsensor_sdk.h
#rm -rf ./selfdrive/camerad/include/msmb_camera.h
#rm -rf ./selfdrive/camerad/include/msmb_isp.h
#rm -rf ./selfdrive/camerad/include/msmb_ispif.h
#rm -rf ./selfdrive/camerad/main.cc
#rm -rf ./selfdrive/camerad/transforms/rgb_to_yuv.cc
#rm -rf ./selfdrive/camerad/transforms/rgb_to_yuv.h
#rm -rf ./selfdrive/camerad/transforms/rgb_to_yuv_test.cc
#rm -rf ./selfdrive/clocksd/clocksd.cc
#rm -rf ./selfdrive/common/clutil.cc
#rm -rf ./selfdrive/common/clutil.h
#rm -rf ./selfdrive/common/framebuffer.cc
#rm -rf ./selfdrive/common/framebuffer.h
#rm -rf ./selfdrive/common/glutil.cc
#rm -rf ./selfdrive/common/glutil.h
#rm -rf ./selfdrive/common/gpio.cc
#rm -rf ./selfdrive/common/gpio.h
#rm -rf ./selfdrive/common/i2c.cc
#rm -rf ./selfdrive/common/i2c.h
#rm -rf ./selfdrive/common/mat.h
#rm -rf ./selfdrive/common/modeldata.h
rm -rf ./selfdrive/common/params.cc
#rm -rf ./selfdrive/common/params.h
#rm -rf ./selfdrive/common/params.o
#rm -rf ./selfdrive/common/queue.h
#rm -rf ./selfdrive/common/swaglog.cc
#rm -rf ./selfdrive/common/swaglog.h
#rm -rf ./selfdrive/common/timing.h
#rm -rf ./selfdrive/common/touch.c
#rm -rf ./selfdrive/common/touch.h
#rm -rf ./selfdrive/common/util.cc
#rm -rf ./selfdrive/common/util.h
#rm -rf ./selfdrive/common/visionimg.cc
#rm -rf ./selfdrive/common/visionimg.h
#rm -rf ./selfdrive/common/watchdog.cc
#rm -rf ./selfdrive/common/watchdog.h
#rm -rf ./selfdrive/controls/lib/cluster/fastcluster.cpp
#rm -rf ./selfdrive/controls/lib/cluster/fastcluster.h
#rm -rf ./selfdrive/controls/lib/cluster/fastcluster_dm.cpp
#rm -rf ./selfdrive/controls/lib/cluster/fastcluster_R_dm.cpp
#rm -rf ./selfdrive/controls/lib/cluster/test.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/generator.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lateral_mpc.c
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_auxiliary_functions.c
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_auxiliary_functions.h
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_common.h
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_integrator.c
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_qpoases_interface.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_qpoases_interface.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_solver.c
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/Bounds.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/Constants.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/Constraints.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/CyclingManager.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/EXTRAS/SolutionAnalysis.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/Indexlist.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/MessageHandling.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/QProblem.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/QProblemB.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/SubjectTo.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/Types.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/INCLUDE/Utils.hpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/Bounds.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/Constraints.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/CyclingManager.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/EXTRAS/SolutionAnalysis.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/Indexlist.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/MessageHandling.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/QProblem.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/QProblemB.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/SubjectTo.cpp
#rm -rf ./selfdrive/controls/lib/lateral_mpc/lib_qp/SRC/Utils.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/generator.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_mpc_export/acado_auxiliary_functions.c
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_mpc_export/acado_auxiliary_functions.h
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_mpc_export/acado_common.h
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_mpc_export/acado_integrator.c
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_mpc_export/acado_qpoases_interface.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_mpc_export/acado_qpoases_interface.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_mpc_export/acado_solver.c
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/Bounds.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/Constants.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/Constraints.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/CyclingManager.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/EXTRAS/SolutionAnalysis.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/Indexlist.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/MessageHandling.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/QProblem.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/QProblemB.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/SubjectTo.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/Types.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/INCLUDE/Utils.hpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/Bounds.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/Constraints.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/CyclingManager.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/EXTRAS/SolutionAnalysis.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/Indexlist.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/MessageHandling.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/QProblem.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/QProblemB.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/SubjectTo.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/lib_qp/SRC/Utils.cpp
#rm -rf ./selfdrive/controls/lib/lead_mpc_lib/longitudinal_mpc.c
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/generator.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_mpc_export/acado_auxiliary_functions.c
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_mpc_export/acado_auxiliary_functions.h
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_mpc_export/acado_common.h
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_mpc_export/acado_integrator.c
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_mpc_export/acado_qpoases_interface.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_mpc_export/acado_qpoases_interface.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_mpc_export/acado_solver.c
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/Bounds.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/Constants.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/Constraints.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/CyclingManager.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/EXTRAS/SolutionAnalysis.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/Indexlist.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/MessageHandling.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/QProblem.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/QProblemB.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/SubjectTo.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/Types.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/INCLUDE/Utils.hpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/Bounds.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/Constraints.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/CyclingManager.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/EXTRAS/SolutionAnalysis.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/Indexlist.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/MessageHandling.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/QProblem.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/QProblemB.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/SubjectTo.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/lib_qp/SRC/Utils.cpp
#rm -rf ./selfdrive/controls/lib/longitudinal_mpc_lib/longitudinal_mpc.c
#rm -rf ./selfdrive/hardware/base.h
#rm -rf ./selfdrive/hardware/eon/hardware.h
#rm -rf ./selfdrive/hardware/hw.h
#rm -rf ./selfdrive/hardware/tici/hardware.h
#rm -rf ./selfdrive/locationd/generated/gps.cpp
#rm -rf ./selfdrive/locationd/generated/gps.h
#rm -rf ./selfdrive/locationd/generated/ubx.cpp
#rm -rf ./selfdrive/locationd/generated/ubx.h
#rm -rf ./selfdrive/locationd/locationd.cc
#rm -rf ./selfdrive/locationd/locationd.h
#rm -rf ./selfdrive/locationd/models/generated/car.cpp
#rm -rf ./selfdrive/locationd/models/generated/car.h
#rm -rf ./selfdrive/locationd/models/generated/live.cpp
#rm -rf ./selfdrive/locationd/models/generated/live.h
#rm -rf ./selfdrive/locationd/models/generated/live_kf_constants.h
#rm -rf ./selfdrive/locationd/models/live_kf.cc
#rm -rf ./selfdrive/locationd/models/live_kf.h
#rm -rf ./selfdrive/locationd/ublox_msg.cc
#rm -rf ./selfdrive/locationd/ublox_msg.h
#rm -rf ./selfdrive/locationd/ubloxd.cc
#rm -rf ./selfdrive/logcatd/logcatd_android.cc
#rm -rf ./selfdrive/logcatd/logcatd_systemd.cc
#rm -rf ./selfdrive/loggerd/bootlog.cc
#rm -rf ./selfdrive/loggerd/encoder.h
#rm -rf ./selfdrive/loggerd/include/msm_media_info.h
#rm -rf ./selfdrive/loggerd/logger.cc
#rm -rf ./selfdrive/loggerd/logger.h
#rm -rf ./selfdrive/loggerd/loggerd.cc
#rm -rf ./selfdrive/loggerd/omx_encoder.cc
#rm -rf ./selfdrive/loggerd/omx_encoder.h
#rm -rf ./selfdrive/loggerd/raw_logger.cc
#rm -rf ./selfdrive/loggerd/raw_logger.h
#rm -rf ./selfdrive/modeld/dmonitoringmodeld.cc
#rm -rf ./selfdrive/modeld/modeld.cc
#rm -rf ./selfdrive/modeld/models/commonmodel.cc
#rm -rf ./selfdrive/modeld/models/commonmodel.h
#rm -rf ./selfdrive/modeld/models/dmonitoring.cc
#rm -rf ./selfdrive/modeld/models/dmonitoring.h
#rm -rf ./selfdrive/modeld/models/driving.cc
#rm -rf ./selfdrive/modeld/models/driving.h
#rm -rf ./selfdrive/modeld/runners/run.h
#rm -rf ./selfdrive/modeld/runners/runmodel.h
#rm -rf ./selfdrive/modeld/runners/snpemodel.cc
#rm -rf ./selfdrive/modeld/runners/snpemodel.h
#rm -rf ./selfdrive/modeld/runners/thneedmodel.cc
#rm -rf ./selfdrive/modeld/runners/thneedmodel.h
#rm -rf ./selfdrive/modeld/thneed/compile.cc
#rm -rf ./selfdrive/modeld/thneed/include/msm_kgsl.h
#rm -rf ./selfdrive/modeld/thneed/serialize.cc
#rm -rf ./selfdrive/modeld/thneed/thneed.cc
#rm -rf ./selfdrive/modeld/thneed/thneed.h
#rm -rf ./selfdrive/modeld/transforms/loadyuv.cc
#rm -rf ./selfdrive/modeld/transforms/loadyuv.h
#rm -rf ./selfdrive/modeld/transforms/transform.cc
#rm -rf ./selfdrive/modeld/transforms/transform.h
#rm -rf ./selfdrive/proclogd/main.cc
#rm -rf ./selfdrive/proclogd/proclog.cc
#rm -rf ./selfdrive/proclogd/proclog.h
#rm -rf ./selfdrive/sensord/libdiag.h
#rm -rf ./selfdrive/sensord/sensors/bmx055_accel.cc
#rm -rf ./selfdrive/sensord/sensors/bmx055_accel.h
#rm -rf ./selfdrive/sensord/sensors/bmx055_gyro.cc
#rm -rf ./selfdrive/sensord/sensors/bmx055_gyro.h
#rm -rf ./selfdrive/sensord/sensors/bmx055_magn.cc
#rm -rf ./selfdrive/sensord/sensors/bmx055_magn.h
#rm -rf ./selfdrive/sensord/sensors/bmx055_temp.cc
#rm -rf ./selfdrive/sensord/sensors/bmx055_temp.h
#rm -rf ./selfdrive/sensord/sensors/constants.h
#rm -rf ./selfdrive/sensord/sensors/file_sensor.cc
#rm -rf ./selfdrive/sensord/sensors/file_sensor.h
#rm -rf ./selfdrive/sensord/sensors/i2c_sensor.cc
#rm -rf ./selfdrive/sensord/sensors/i2c_sensor.h
#rm -rf ./selfdrive/sensord/sensors/light_sensor.cc
#rm -rf ./selfdrive/sensord/sensors/light_sensor.h
#rm -rf ./selfdrive/sensord/sensors/lsm6ds3_accel.cc
#rm -rf ./selfdrive/sensord/sensors/lsm6ds3_accel.h
#rm -rf ./selfdrive/sensord/sensors/lsm6ds3_gyro.cc
#rm -rf ./selfdrive/sensord/sensors/lsm6ds3_gyro.h
#rm -rf ./selfdrive/sensord/sensors/lsm6ds3_temp.cc
#rm -rf ./selfdrive/sensord/sensors/lsm6ds3_temp.h
#rm -rf ./selfdrive/sensord/sensors/mmc5603nj_magn.cc
#rm -rf ./selfdrive/sensord/sensors/mmc5603nj_magn.h
#rm -rf ./selfdrive/sensord/sensors/sensor.h
#rm -rf ./selfdrive/sensord/sensors_qcom.cc
#rm -rf ./selfdrive/sensord/sensors_qcom.o
#rm -rf ./selfdrive/sensord/sensors_qcom2.cc
rm -rf ./selfdrive/ui/main.cc
rm -rf ./selfdrive/ui/moc_ui.cc
rm -rf ./selfdrive/ui/paint.cc
rm -rf ./selfdrive/ui/paint.h
rm -rf ./selfdrive/ui/qt/api.cc
rm -rf ./selfdrive/ui/qt/api.h
rm -rf ./selfdrive/ui/qt/home.cc
rm -rf ./selfdrive/ui/qt/home.h
rm -rf ./selfdrive/ui/qt/maps/map.cc
rm -rf ./selfdrive/ui/qt/maps/map.h
rm -rf ./selfdrive/ui/qt/maps/map_helpers.cc
rm -rf ./selfdrive/ui/qt/maps/map_helpers.h
rm -rf ./selfdrive/ui/qt/maps/map_settings.cc
rm -rf ./selfdrive/ui/qt/maps/map_settings.h
rm -rf ./selfdrive/ui/qt/maps/moc_map.cc
rm -rf ./selfdrive/ui/qt/maps/moc_map_settings.cc
rm -rf ./selfdrive/ui/qt/moc_api.cc
rm -rf ./selfdrive/ui/qt/moc_home.cc
rm -rf ./selfdrive/ui/qt/moc_onroad.cc
rm -rf ./selfdrive/ui/qt/moc_sidebar.cc
rm -rf ./selfdrive/ui/qt/moc_spinner.cc
rm -rf ./selfdrive/ui/qt/moc_util.cc
rm -rf ./selfdrive/ui/qt/moc_window.cc
rm -rf ./selfdrive/ui/qt/moc_speed_camera.cc
rm -rf ./selfdrive/ui/qt/moc_vag_param.cc
rm -rf ./selfdrive/ui/qt/offroad/driverview.cc
rm -rf ./selfdrive/ui/qt/offroad/driverview.h
rm -rf ./selfdrive/ui/qt/offroad/moc_driverview.cc
rm -rf ./selfdrive/ui/qt/offroad/moc_onboarding.cc
rm -rf ./selfdrive/ui/qt/offroad/moc_settings.cc
rm -rf ./selfdrive/ui/qt/offroad/networking.cc
rm -rf ./selfdrive/ui/qt/offroad/networking.h
rm -rf ./selfdrive/ui/qt/offroad/networkmanager.h
rm -rf ./selfdrive/ui/qt/offroad/onboarding.cc
rm -rf ./selfdrive/ui/qt/offroad/onboarding.h
rm -rf ./selfdrive/ui/qt/offroad/settings.cc
rm -rf ./selfdrive/ui/qt/offroad/settings.h
rm -rf ./selfdrive/ui/qt/offroad/wifiManager.cc
rm -rf ./selfdrive/ui/qt/offroad/wifiManager.h
rm -rf ./selfdrive/ui/qt/onroad.cc
rm -rf ./selfdrive/ui/qt/onroad.h
rm -rf ./selfdrive/ui/qt/qt_window.h
rm -rf ./selfdrive/ui/qt/request_repeater.cc
rm -rf ./selfdrive/ui/qt/request_repeater.h
rm -rf ./selfdrive/ui/qt/sidebar.cc
rm -rf ./selfdrive/ui/qt/sidebar.h
rm -rf ./selfdrive/ui/qt/spinner.cc
rm -rf ./selfdrive/ui/qt/spinner.h
rm -rf ./selfdrive/ui/qt/text.cc
rm -rf ./selfdrive/ui/qt/util.cc
rm -rf ./selfdrive/ui/qt/util.h
rm -rf ./selfdrive/ui/qt/widgets/cameraview.cc
rm -rf ./selfdrive/ui/qt/widgets/cameraview.h
rm -rf ./selfdrive/ui/qt/widgets/cameraview.o
rm -rf ./selfdrive/ui/qt/widgets/controls.cc
rm -rf ./selfdrive/ui/qt/widgets/controls.h
rm -rf ./selfdrive/ui/qt/widgets/drive_stats.cc
rm -rf ./selfdrive/ui/qt/widgets/drive_stats.h
rm -rf ./selfdrive/ui/qt/widgets/input.cc
rm -rf ./selfdrive/ui/qt/widgets/input.h
rm -rf ./selfdrive/ui/qt/widgets/keyboard.cc
rm -rf ./selfdrive/ui/qt/widgets/keyboard.h
rm -rf ./selfdrive/ui/qt/widgets/moc_cameraview.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_controls.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_drive_stats.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_input.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_keyboard.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_offroad_alerts.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_prime.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_scrollview.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_setup.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_ssh_keys.cc
rm -rf ./selfdrive/ui/qt/widgets/moc_toggle.cc
rm -rf ./selfdrive/ui/qt/widgets/offroad_alerts.cc
rm -rf ./selfdrive/ui/qt/widgets/offroad_alerts.h
rm -rf ./selfdrive/ui/qt/widgets/prime.cc
rm -rf ./selfdrive/ui/qt/widgets/prime.h
rm -rf ./selfdrive/ui/qt/widgets/scrollview.cc
rm -rf ./selfdrive/ui/qt/widgets/scrollview.h
rm -rf ./selfdrive/ui/qt/widgets/ssh_keys.cc
rm -rf ./selfdrive/ui/qt/widgets/ssh_keys.h
rm -rf ./selfdrive/ui/qt/widgets/toggle.cc
rm -rf ./selfdrive/ui/qt/widgets/toggle.h
rm -rf ./selfdrive/ui/qt/window.cc
rm -rf ./selfdrive/ui/qt/window.h
rm -rf ./selfdrive/ui/soundd.cc
rm -rf ./selfdrive/ui/ui.cc
rm -rf ./selfdrive/ui/ui.h

rm -rf ./panda/board/main.c
rm -rf ./panda/board/safety/safety_volkswagen_mqb.h
rm -rf ./selfdrive/hardware/eon/hardware.h
rm -rf ./selfdrive/ui/SConscript
rm -rf ./selfdrive/ui/qt/debug.cc
rm -rf ./selfdrive/ui/qt/debug.h
rm -rf ./selfdrive/ui/qt/home.cc
rm -rf ./selfdrive/ui/qt/home.h
rm -rf ./selfdrive/ui/qt/offroad/settings.cc
rm -rf ./selfdrive/ui/qt/offroad/settings.h
rm -rf ./selfdrive/ui/qt/onroad.cc
rm -rf ./selfdrive/ui/qt/onroad.h
rm -rf ./selfdrive/ui/qt/sidebar.cc
rm -rf ./selfdrive/ui/qt/sidebar.h
rm -rf ./selfdrive/ui/qt/util.cc
rm -rf ./selfdrive/ui/qt/widgets/controls.h
rm -rf ./selfdrive/ui/qt/window.cc
rm -rf ./selfdrive/ui/qt/window.h
rm -rf ./selfdrive/ui/soundd/sound.cc
rm -rf ./selfdrive/ui/soundd/sound.h
rm -rf ./selfdrive/ui/ui.cc
rm -rf ./selfdrive/ui/ui.h

